# -*- coding: utf-8 -*-
"""RASTRO-L.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZIjYJE6qfSOVYggxF9HfO0JcVoG77Ff
"""

# RASTRO-L

import csv
import gc
import json
import math
import os
import random
import re
import shutil
import subprocess
import sys
import time
import urllib.request
from collections import defaultdict
from pathlib import Path

ACCESSION = "SRR10605873"
MODEL_NAME = "evo2_7b_base"
CONTEXT_LENGTHS = [5, 6, 7, 10]
LOOKAHEAD_HOPS = 3
EXT_BP_LIMIT = 512
OVERLAP = 30
KMER_K = 31
N_SAMPLE_BRANCHES = 20000
RANDOM_SEED = 13
BATCH_SIZE = 4
MAX_EXT_LEN = 512
RESUME = True
MARGIN_THRESHOLDS = [5, 10]
BOUNDARY_CONTEXT_LEN = 31

EVO2_PYTHON = Path("/tmp/evo2-venv/bin/python")
ROOT = Path("/content/rastro_l")
ROOT.mkdir(parents=True, exist_ok=True)

random.seed(RANDOM_SEED)


def run(cmd, cwd=None, check=True, timeout=None):
    p = subprocess.run(
        [str(x) for x in cmd],
        cwd=str(cwd) if cwd else None,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        timeout=timeout,
    )
    if p.stdout:
        print(p.stdout)
    if check and p.returncode != 0:
        raise RuntimeError(f"Command failed ({p.returncode}): {' '.join(map(str, cmd))}")
    return p


def revcomp(seq: str) -> str:
    table = str.maketrans("ACGTNacgtn", "TGCANtgcan")
    return seq.translate(table)[::-1].upper()


def rebuild_evo2_environment():
    print("=" * 80)
    print("RASTRO / EVO2 BLACKWELL ENVIRONMENT REBUILD")
    print("=" * 80)

    ENV = Path("/tmp/evo2-venv")
    PYTHON = ENV / "bin" / "python"
    PIP = [str(PYTHON), "-m", "pip"]

    def _run(cmd, label, check=True):
        print("\n" + "-" * 80)
        print(label)
        print("$", " ".join(str(x) for x in cmd))
        print("-" * 80)
        p = subprocess.run(
            [str(x) for x in cmd],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        if p.stdout:
            print(p.stdout)
        if check and p.returncode != 0:
            raise RuntimeError(f"\nCOMMAND FAILED ({p.returncode}): {label}")
        return p

    print("\nHOST PYTHON:")
    print(sys.version)
    print("Executable:", sys.executable)

    _run(
        ["nvidia-smi", "--query-gpu=name,memory.total,driver_version", "--format=csv,noheader"],
        "Checking NVIDIA GPU",
    )

    uv = "uv"
    p = subprocess.run(["bash", "-lc", "command -v uv"], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if p.returncode != 0:
        raise RuntimeError("uv was not found.")
    print("\nuv:", p.stdout.strip())

    if not PYTHON.exists():
        print("\nPython 3.11 environment is missing. Creating:", ENV)
        if ENV.exists():
            _run(["rm", "-rf", str(ENV)], "Removing incomplete Evo2 environment")
        _run([uv, "venv", "--python", "3.11.15", str(ENV)], "Creating Python 3.11.15 environment")
    else:
        print("\nExisting Python 3.11 environment found:", PYTHON)

    _run([str(PYTHON), "--version"], "Verifying Python 3.11")

    pip_check = subprocess.run(PIP + ["--version"], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    print("\nPip check:")
    print(pip_check.stdout)
    if pip_check.returncode != 0:
        _run([str(PYTHON), "-m", "ensurepip", "--upgrade"], "Bootstrapping pip")

    _run(PIP + ["install", "--upgrade", "pip", "setuptools", "wheel"], "Updating pip/setuptools/wheel")

    print("\nInstalling validated PyTorch CUDA 12.8 stack...")
    _run(
        PIP + [
            "install",
            "--index-url", "https://download.pytorch.org/whl/cu128",
            "torch==2.7.1",
            "torchvision==0.22.1",
            "torchaudio==2.7.1",
        ],
        "Installing PyTorch 2.7.1 + CUDA 12.8",
    )

    torch_test = r'''
import torch
print("PyTorch:", torch.__version__)
print("Torch CUDA:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU count:", torch.cuda.device_count())
if not torch.cuda.is_available():
    raise RuntimeError("CUDA is not available.")
name = torch.cuda.get_device_name(0)
props = torch.cuda.get_device_properties(0)
print("GPU:", name)
print("VRAM GB:", round(props.total_memory / 1024**3, 2))
print("Compute capability:", f"{props.major}.{props.minor}")
a = torch.randn((1024, 1024), device="cuda", dtype=torch.float16)
b = torch.randn((1024, 1024), device="cuda", dtype=torch.float16)
c = a @ b
torch.cuda.synchronize()
print("CUDA matrix test: PASS")
print("Result finite:", bool(torch.isfinite(c).all()))
del a, b, c
torch.cuda.empty_cache()
'''
    _run([str(PYTHON), "-c", torch_test], "Verifying PyTorch CUDA/Blackwell")

    flash_dir = ENV / "flash_wheels"
    flash_dir.mkdir(parents=True, exist_ok=True)
    flash_name = "flash_attn-2.8.0.post2+cu12torch2.7cxx11abiTRUE-cp311-cp311-linux_x86_64.whl"
    flash_url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.0.post2/" + flash_name
    flash_path = flash_dir / flash_name
    if not flash_path.exists():
        print("\nDownloading official FlashAttention wheel...")
        print(flash_url)
        urllib.request.urlretrieve(flash_url, flash_path)
    print("\nFlashAttention wheel:", flash_path)
    _run(PIP + ["install", "--no-deps", "--force-reinstall", str(flash_path)], "Installing FlashAttention 2.8.0.post2")

    flash_test = r'''
import torch
import flash_attn
from flash_attn import flash_attn_func
print("FlashAttention:", getattr(flash_attn, "__version__", "unknown"))
print("flash_attn_func import: PASS")
q = torch.randn((1, 16, 4, 64), device="cuda", dtype=torch.bfloat16)
k = torch.randn((1, 16, 4, 64), device="cuda", dtype=torch.bfloat16)
v = torch.randn((1, 16, 4, 64), device="cuda", dtype=torch.bfloat16)
out = flash_attn_func(q, k, v)
torch.cuda.synchronize()
print("FlashAttention CUDA test: PASS")
print("Output shape:", tuple(out.shape))
print("Output dtype:", out.dtype)
print("Output device:", out.device)
print("Output finite:", bool(torch.isfinite(out).all()))
del q, k, v, out
torch.cuda.empty_cache()
'''
    _run([str(PYTHON), "-c", flash_test], "Verifying FlashAttention on Blackwell")

    evo2_check = subprocess.run(PIP + ["show", "evo2"], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if "Name: evo2" not in evo2_check.stdout:
        _run(PIP + ["install", "--no-deps", "evo2==0.6.0"], "Installing Evo2 0.6.0")
    else:
        print("\nEvo2 0.6.0 already installed.")

    _run(
        PIP + [
            "install",
            "huggingface_hub==1.32.0",
            "vtx==1.1.0",
            "biopython==1.88",
            "httpx==0.28.1",
            "httpcore==1.0.9",
            "h11==0.16.0",
            "idna==3.20",
            "anyio==4.15.1",
            "certifi==2026.7.22",
            "tqdm==4.70.1",
            "filelock==4.0.0",
            "fsspec==2026.9.0",
            "packaging==26.3",
            "pyyaml==6.0.3",
            "requests==2.34.2",
            "einops==0.8.1",
            "rich==15.0.0",
        ],
        "Installing validated Evo2 dependencies",
    )

    import_test = r'''
import torch
import flash_attn
from flash_attn import flash_attn_func
from evo2 import Evo2
print("torch:", torch.__version__)
print("torch CUDA:", torch.version.cuda)
print("flash-attn:", getattr(flash_attn, "__version__", "unknown"))
print("Evo2:", Evo2)
print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))
if not torch.cuda.is_available():
    raise RuntimeError("CUDA unavailable after environment rebuild.")
print("ENVIRONMENT IMPORT TEST: PASS")
'''
    _run([str(PYTHON), "-c", import_test], "Final package/import verification")

    model_test = r'''
import torch
from evo2 import Evo2
print("=" * 70)
print("LOADING EVO2_7B_BASE")
print("=" * 70)
model = Evo2("evo2_7b_base")
print("\nMODEL LOAD: PASS")
seq = "ACGTACGTACGTACGTACGTACGTACGTACGT"
token_ids = model.tokenizer.tokenize(seq)
input_ids = torch.tensor(token_ids, dtype=torch.long, device="cuda").unsqueeze(0)
print("\nInput:")
print("Sequence length:", len(seq))
print("Input shape:", tuple(input_ids.shape))
print("Input dtype:", input_ids.dtype)
print("Input device:", input_ids.device)
with torch.inference_mode():
    output = model(input_ids)
logits = output[0][0]
print("\nLogits:")
print("Shape:", tuple(logits.shape))
print("Dtype:", logits.dtype)
print("Device:", logits.device)
print("Finite:", bool(torch.isfinite(logits).all()))
expected_shape = (1, len(seq), 512)
if tuple(logits.shape) != expected_shape:
    raise RuntimeError(f"Unexpected logits shape: {tuple(logits.shape)}; expected {expected_shape}")
if logits.device.type != "cuda":
    raise RuntimeError("Evo2 logits are not on CUDA.")
print("\n" + "=" * 70)
print("EVO2_7B_BASE FORWARD TEST: PASS")
print("=" * 70)
print("\nCUDA memory:")
print("Allocated GB:", round(torch.cuda.memory_allocated() / 1024**3, 2))
print("Reserved GB:", round(torch.cuda.memory_reserved() / 1024**3, 2))
'''
    _run([str(PYTHON), "-c", model_test], "End-to-end evo2_7b_base load + forward test")

    print("\n")
    print("=" * 80)
    print("BLACKWELL EVO2 ENVIRONMENT READY")
    print("=" * 80)
    print("Python:", PYTHON)
    print("Environment:", ENV)
    print("Model:", "evo2_7b_base")
    print("PyTorch:", "2.7.1 + CUDA 12.8")
    print("FlashAttention:", "2.8.0.post2")
    print("Evo2:", "0.6.0")
    print("=" * 80)
    print("\nIMPORTANT: Later Evo2 subprocesses must use:\n  " + str(PYTHON) + "\n")


def parse_unitigs(fa_path: Path):
    unitigs = {}
    links = []
    name = None
    seq = []
    with fa_path.open() as fh:
        for line in fh:
            if line.startswith(">"):
                if name is not None:
                    m = re.search(r"(\d+)$", name)
                    if m:
                        uid = int(m.group(1))
                        unitigs[uid] = {"name": name, "seq": "".join(seq).upper()}
                        for mlink in re.finditer(r"L:([+-]):([^:]+):([+-])", name):
                            our, nid_token, nor = mlink.groups()
                            mid = re.search(r"(\d+)$", nid_token)
                            if mid:
                                links.append((uid, our, int(mid.group(1)), nor))
                name = line[1:].strip().split()[0]
                seq = []
            else:
                seq.append(line.strip())
        if name is not None:
            m = re.search(r"(\d+)$", name)
            if m:
                uid = int(m.group(1))
                unitigs[uid] = {"name": name, "seq": "".join(seq).upper()}
                for mlink in re.finditer(r"L:([+-]):([^:]+):([+-])", name):
                    our, nid_token, nor = mlink.groups()
                    mid = re.search(r"(\d+)$", nid_token)
                    if mid:
                        links.append((uid, our, int(mid.group(1)), nor))
    return unitigs, links


def oriented_seq(unitigs, uid, orient):
    seq = unitigs[uid]["seq"]
    return seq if orient == "+" else revcomp(seq)


def neighbors(unitigs, links, uid, orient):
    out = []
    for src, our, tgt, nor in links:
        if src == uid and our == orient:
            out.append((tgt, nor))
    return out


def prepare_candidates():
    print("\n" + "#" * 80)
    print("ACCESSION:", ACCESSION)
    print("#" * 80)

    outdir = ROOT / ACCESSION
    outdir.mkdir(parents=True, exist_ok=True)

    unitig_fa = outdir / f"{ACCESSION}.unitigs.fa"
    if not unitig_fa.exists():
        zst_url = f"https://logan-pub.s3.amazonaws.com/u/{ACCESSION}/{ACCESSION}.unitigs.fa.zst"
        zst_path = outdir / f"{ACCESSION}.unitigs.fa.zst"
        print("Downloading:", zst_url)
        subprocess.run(["curl", "-fsSL", zst_url, "-o", str(zst_path)], check=True)
        subprocess.run(["zstd", "-d", "-f", str(zst_path), "-o", str(unitig_fa)], check=True)

    unitigs, links = parse_unitigs(unitig_fa)
    print("Unitigs:", len(unitigs))
    print("Links:", len(links))

    branches = []
    for uid in unitigs:
        for side in ["+", "-"]:
            outs = neighbors(unitigs, links, uid, side)
            if len(outs) >= 2:
                branches.append((uid, side, outs))
    print("Branching points:", len(branches))

    candidate_rows = []
    for uid, side, outs in branches:
        for cand_idx, (tgt, tor) in enumerate(outs):
            nodes = []
            ext_chunks = []
            bases = 0
            hops = 0
            cur_uid, cur_or = tgt, tor
            visited = {(uid, side)}
            while True:
                if (cur_uid, cur_or) in visited:
                    break
                visited.add((cur_uid, cur_or))
                if cur_uid not in unitigs:
                    break
                seq = oriented_seq(unitigs, cur_uid, cur_or)
                nodes.append(f"{cur_uid}{cur_or}")
                if len(seq) <= OVERLAP:
                    break
                suffix = seq[OVERLAP:]
                take = min(len(suffix), max(0, EXT_BP_LIMIT - bases))
                if take <= 0:
                    break
                ext_chunks.append(suffix[:take])
                bases += take
                if bases >= EXT_BP_LIMIT:
                    break
                outs2 = neighbors(unitigs, links, cur_uid, cur_or)
                if len(outs2) != 1:
                    break
                cur_uid, cur_or = outs2[0]
                hops += 1
                if hops >= LOOKAHEAD_HOPS:
                    break
            if bases > 0:
                candidate_rows.append({
                    "branch_key": f"{unitigs[uid]['name']}|{side}",
                    "branch_unitig_id": uid,
                    "branch_side": side,
                    "candidate_index": cand_idx,
                    "first_target_unitig_id": tgt,
                    "first_target_orientation": tor,
                    "path_nodes": "->".join(nodes),
                    "extension": "".join(ext_chunks),
                    "extension_length": bases,
                    "hops": hops,
                })
    print("Total valid candidate extensions:", len(candidate_rows))

    candidates_by_branch = {}
    for row in candidate_rows:
        candidates_by_branch.setdefault(row["branch_key"], []).append(row)

    comparable_branches = [key for key, rows in candidates_by_branch.items() if len(rows) >= 2]
    print("Branches with >=2 valid candidates:", len(comparable_branches))

    if len(comparable_branches) > N_SAMPLE_BRANCHES:
        sampled_keys = random.sample(comparable_branches, N_SAMPLE_BRANCHES)
    else:
        sampled_keys = list(comparable_branches)
    sampled_keys = sorted(sampled_keys)
    sampled_set = set(sampled_keys)
    sampled_candidates = [row for row in candidate_rows if row["branch_key"] in sampled_set]
    print("Sampled branches:", len(sampled_keys))
    print("Candidates in sampled branches:", len(sampled_candidates))

    sampled_branches_csv = outdir / "sampled_branches.csv"
    with sampled_branches_csv.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["branch_key", "branch_unitig_id", "branch_side", "n_candidates"])
        for key in sampled_keys:
            rows = candidates_by_branch[key]
            first = rows[0]
            w.writerow([key, first["branch_unitig_id"], first["branch_side"], len(rows)])

    candidates_csv = outdir / "candidate_extensions.csv"
    with candidates_csv.open("w", newline="") as fh:
        fields = [
            "branch_key", "branch_unitig_id", "branch_side", "candidate_index",
            "first_target_unitig_id", "first_target_orientation", "path_nodes",
            "extension", "extension_length", "hops",
        ]
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        for row in sampled_candidates:
            w.writerow(row)

    print("\n" + "-" * 80)
    print("PREPARING EVO2 CONTEXTS")
    print("-" * 80)

    scoring_rows = []
    for row in sampled_candidates:
        uid = row["branch_unitig_id"]
        side = row["branch_side"]
        source_seq = unitigs[uid]["seq"]
        oriented_source = revcomp(source_seq) if side == "-" else source_seq
        for context_length in CONTEXT_LENGTHS:
            if len(oriented_source) < context_length:
                continue
            context = oriented_source[-context_length:]
            scoring_rows.append({
                "accession": ACCESSION,
                "branch_key": row["branch_key"],
                "branch_unitig_id": uid,
                "branch_side": side,
                "candidate_index": row["candidate_index"],
                "path_nodes": row["path_nodes"],
                "context_length": context_length,
                "context": context,
                "extension": row["extension"],
                "extension_length": row["extension_length"],
            })

    scoring_inputs_csv = outdir / "evo2_scoring_inputs.csv"
    fields = [
        "accession", "branch_key", "branch_unitig_id", "branch_side",
        "candidate_index", "path_nodes", "context_length", "context",
        "extension", "extension_length",
    ]
    with scoring_inputs_csv.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        for row in scoring_rows:
            w.writerow(row)

    print("\n" + "=" * 80)
    print("GRAPH / CANDIDATE PREPARATION COMPLETE")
    print("=" * 80)
    print("Unitigs:", len(unitigs))
    print("Graph links:", len(links))
    print("Branching points:", len(branches))
    print("Branches with >=2 candidates:", len(comparable_branches))
    print("Sampled branches:", len(sampled_keys))
    print("Sampled candidates:", len(sampled_candidates))
    print("Evo2 scoring rows:", len(scoring_rows))
    print("\nFiles:")
    print("  Sampled branches:", sampled_branches_csv)
    print("  Candidates:", candidates_csv)
    print("  Evo2 inputs:", scoring_inputs_csv)

    return outdir


def score_with_evo2(outdir: Path):
    print("\n" + "-" * 80)
    print("STAGE 1 — EVO2 SCORING")
    print("-" * 80)

    scoring_inputs = outdir / "evo2_scoring_inputs.csv"
    scored_csv = outdir / "evo2_scored_candidates.csv"
    decisions_csv = outdir / "evo2_branch_decisions.csv"

    if not scoring_inputs.exists():
        raise RuntimeError(f"Missing {scoring_inputs}. Run preparation first.")

    rows = []
    with scoring_inputs.open() as fh:
        for r in csv.DictReader(fh):
            rows.append(r)
    print(f"Scoring rows to process: {len(rows)}")

    already = set()
    if RESUME and scored_csv.exists():
        with scored_csv.open() as fh:
            for r in csv.DictReader(fh):
                key = (r["branch_key"], r["candidate_index"], r["context_length"])
                already.add(key)
        print(f"Resuming — {len(already)} rows already scored")

    todo = [
        r for r in rows
        if (r["branch_key"], r["candidate_index"], r["context_length"]) not in already
    ]
    print(f"Remaining: {len(todo)}")

    if todo:
        work_jsonl = outdir / "_scoring_work.jsonl"
        with work_jsonl.open("w") as fh:
            for r in todo:
                fh.write(json.dumps({
                    "branch_key": r["branch_key"],
                    "candidate_index": int(r["candidate_index"]),
                    "context_length": int(r["context_length"]),
                    "context": r["context"],
                    "extension": r["extension"][:MAX_EXT_LEN],
                }) + "\n")

        score_script = r'''
import csv
import gc
import json
import math
import sys
import torch
from pathlib import Path
from evo2 import Evo2

MODEL_NAME = sys.argv[1]
WORK_JSONL = Path(sys.argv[2])
OUT_CSV = Path(sys.argv[3])
BATCH_SIZE = int(sys.argv[4])

print("Loading model:", MODEL_NAME)
model = Evo2(MODEL_NAME)
print("Model loaded")

def tokenize(seq):
    return list(model.tokenizer.tokenize(seq))

def score_one(context, extension):
    full = context + extension
    ids = tokenize(full)
    ctx_ids = tokenize(context)
    ext_ids = tokenize(extension)
    if len(ids) != len(ctx_ids) + len(ext_ids):
        raise RuntimeError("Token length mismatch")
    if len(ext_ids) == 0:
        return None, None
    input_ids = torch.tensor(ids, dtype=torch.long, device="cuda").unsqueeze(0)
    with torch.inference_mode():
        out = model(input_ids)
    logits = out[0][0]
    log_probs = torch.log_softmax(logits.float(), dim=-1)
    start = len(ctx_ids) - 1
    end = start + len(ext_ids)
    pos_log_probs = log_probs[0, start:end, :]
    token_ids = torch.tensor(ext_ids, dtype=torch.long, device="cuda")
    token_lps = pos_log_probs[torch.arange(len(ext_ids), device="cuda"), token_ids]
    total_lp = float(token_lps.sum().item())
    bpb = -(total_lp / len(ext_ids) / math.log(2.0))
    return total_lp, bpb

write_header = not OUT_CSV.exists() or OUT_CSV.stat().st_size == 0
with OUT_CSV.open("a", newline="") as out_fh:
    writer = csv.DictWriter(out_fh, fieldnames=[
        "branch_key", "candidate_index", "context_length",
        "context", "extension", "extension_length",
        "total_log_prob", "bpb_L",
    ])
    if write_header:
        writer.writeheader()
    batch = []
    processed = 0
    with WORK_JSONL.open() as fh:
        for line in fh:
            batch.append(json.loads(line))
            if len(batch) < BATCH_SIZE:
                continue
            for item in batch:
                try:
                    lp, bpb = score_one(item["context"], item["extension"])
                    if lp is None:
                        continue
                    writer.writerow({
                        "branch_key": item["branch_key"],
                        "candidate_index": item["candidate_index"],
                        "context_length": item["context_length"],
                        "context": item["context"],
                        "extension": item["extension"],
                        "extension_length": len(item["extension"]),
                        "total_log_prob": f"{lp:.10f}",
                        "bpb_L": f"{bpb:.10f}",
                    })
                except Exception as e:
                    print("ERROR scoring", item["branch_key"], item["candidate_index"], e)
            out_fh.flush()
            processed += len(batch)
            print(f"Scored {processed} candidates")
            batch = []
            gc.collect()
            torch.cuda.empty_cache()
        for item in batch:
            try:
                lp, bpb = score_one(item["context"], item["extension"])
                if lp is None:
                    continue
                writer.writerow({
                    "branch_key": item["branch_key"],
                    "candidate_index": item["candidate_index"],
                    "context_length": item["context_length"],
                    "context": item["context"],
                    "extension": item["extension"],
                    "extension_length": len(item["extension"]),
                    "total_log_prob": f"{lp:.10f}",
                    "bpb_L": f"{bpb:.10f}",
                })
            except Exception as e:
                print("ERROR scoring", item["branch_key"], item["candidate_index"], e)
        out_fh.flush()

print("SCORING COMPLETE")
del model
gc.collect()
torch.cuda.empty_cache()
'''
        script_path = outdir / "_score_evo2.py"
        script_path.write_text(score_script)

        print("Launching Evo2 scoring subprocess (this can take a long time)...")
        run([
            str(EVO2_PYTHON), str(script_path),
            MODEL_NAME,
            str(work_jsonl),
            str(scored_csv),
            str(BATCH_SIZE),
        ], timeout=None)
        print("Evo2 scoring finished.")
    else:
        print("Nothing left to score.")

    print("\nBuilding branch decisions...")
    groups = defaultdict(list)
    with scored_csv.open() as fh:
        for r in csv.DictReader(fh):
            key = (r["branch_key"], int(r["context_length"]))
            groups[key].append({
                "candidate_index": int(r["candidate_index"]),
                "extension": r["extension"],
                "bpb_L": float(r["bpb_L"]),
                "total_log_prob": float(r["total_log_prob"]),
                "extension_length": int(r["extension_length"]),
            })

    decisions = []
    for (branch_key, ctx_len), cands in groups.items():
        if len(cands) < 2:
            continue
        cands.sort(key=lambda x: (x["bpb_L"], x["extension"]))
        best = cands[0]
        decisions.append({
            "branch_key": branch_key,
            "context_length": ctx_len,
            "n_candidates": len(cands),
            "selected_candidate_index": best["candidate_index"],
            "selected_extension": best["extension"],
            "selected_bpb_L": best["bpb_L"],
        })

    with decisions_csv.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=[
            "branch_key", "context_length", "n_candidates",
            "selected_candidate_index", "selected_extension", "selected_bpb_L",
        ])
        w.writeheader()
        for d in decisions:
            w.writerow(d)
    print(f"Branch decisions written: {len(decisions)}")
    return decisions


def fetch_reads_and_evaluate(outdir: Path, decisions):
    print("\n" + "-" * 80)
    print("STAGE 2 — RAW READS + JELLYFISH")
    print("-" * 80)

    candidates_csv = outdir / "candidate_extensions.csv"
    unitig_fa = outdir / f"{ACCESSION}.unitigs.fa"
    scored_csv = outdir / "evo2_scored_candidates.csv"
    decisions_csv = outdir / "evo2_branch_decisions.csv"
    read_choices_csv = outdir / "read_supported_choices.csv"
    match_csv = outdir / "match_results.csv"
    summary_json = outdir / "final_summary.json"

    reads_dir = outdir / "reads"
    reads_dir.mkdir(exist_ok=True)
    jf_db = outdir / f"{ACCESSION}.k{KMER_K}.jf"
    jf_counts = outdir / f"{ACCESSION}.k{KMER_K}.counts"

    def download_with_curl(url: str, dest: Path, retries: int = 4) -> bool:
        dest.parent.mkdir(parents=True, exist_ok=True)
        for attempt in range(1, retries + 1):
            print(f"  curl attempt {attempt}: {url}")
            cmd = ["curl", "-L", "--fail", "--retry", "3", "--connect-timeout", "30", "-o", str(dest), url]
            p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
            if p.returncode == 0 and dest.exists() and dest.stat().st_size > 1000:
                print(f"  OK → {dest} ({dest.stat().st_size/1e6:.1f} MB)")
                return True
            print(f"  failed (rc={p.returncode})")
            if dest.exists():
                dest.unlink(missing_ok=True)
            time.sleep(2 * attempt)
        return False

    for tool in ["curl", "zstd", "jellyfish"]:
        if shutil.which(tool) is None:
            print(f"Installing {tool}...")
            run(["bash", "-lc", f"apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq {tool}"])

    fastq_files = sorted(
        list(reads_dir.glob("*.fastq")) +
        list(reads_dir.glob("*.fq")) +
        list(reads_dir.glob("*.fastq.gz")) +
        list(reads_dir.glob("*.fq.gz"))
    )

    if not fastq_files:
        print("No local FASTQ – trying public mirrors...")
        candidates = [
            f"https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR106/073/{ACCESSION}/{ACCESSION}_1.fastq.gz",
            f"https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR106/073/{ACCESSION}/{ACCESSION}_2.fastq.gz",
            f"https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR106/073/{ACCESSION}/{ACCESSION}.fastq.gz",
        ]
        for url in candidates:
            name = url.rstrip("/").split("/")[-1]
            dest = reads_dir / name
            if dest.exists() and dest.stat().st_size > 1000:
                print(f"Already present: {dest}")
                continue
            download_with_curl(url, dest)

        fastq_files = sorted(
            list(reads_dir.glob("*.fastq")) +
            list(reads_dir.glob("*.fq")) +
            list(reads_dir.glob("*.fastq.gz")) +
            list(reads_dir.glob("*.fq.gz"))
        )

    if not fastq_files:
        print("\nTrying ENA portal API...")
        try:
            api = f"https://www.ebi.ac.uk/ena/portal/api/filereport?accession={ACCESSION}&result=read_run&fields=fastq_ftp,fastq_aspera,fastq_md5&format=json"
            with urllib.request.urlopen(api, timeout=30) as resp:
                meta = json.loads(resp.read().decode())
            if meta:
                ftp_field = meta[0].get("fastq_ftp") or ""
                for part in ftp_field.split(";"):
                    part = part.strip()
                    if not part:
                        continue
                    url = "https://" + part if not part.startswith("http") else part
                    name = url.split("/")[-1]
                    dest = reads_dir / name
                    download_with_curl(url, dest)
        except Exception as e:
            print("ENA API failed:", e)

        fastq_files = sorted(set(
            list(reads_dir.glob("*.fastq")) +
            list(reads_dir.glob("*.fq")) +
            list(reads_dir.glob("*.fastq.gz")) +
            list(reads_dir.glob("*.fq.gz"))
        ))

    if not fastq_files:
        raise RuntimeError(
            f"Could not obtain any FASTQ for {ACCESSION}.\n"
            f"Place them manually in {reads_dir} and re-run."
        )

    print("\nFASTQ files ready:")
    for f in fastq_files:
        print(f"  {f}  ({f.stat().st_size/1e6:.1f} MB)")

    print("\n" + "-" * 80)
    print("JELLYFISH")
    print("-" * 80)

    import gzip
    decompressed_fastq = []
    for fq in fastq_files:
        if fq.name.endswith(".gz"):
            out_fq = fq.with_suffix("")
            if not out_fq.exists():
                print(f"Decompressing: {fq.name} -> {out_fq.name}")
                with gzip.open(fq, "rb") as src, open(out_fq, "wb") as dst:
                    shutil.copyfileobj(src, dst)
            decompressed_fastq.append(out_fq)
        else:
            decompressed_fastq.append(fq)

    if not jf_db.exists():
        print("Counting k-mers (k =", KMER_K, ")...")
        cmd = [
            "jellyfish", "count",
            "-m", str(KMER_K),
            "-s", "2G",
            "-t", "8",
            "-C",
            "-o", str(jf_db),
        ] + [str(f) for f in decompressed_fastq]
        run(cmd)
    print("DB:", jf_db, f"({jf_db.stat().st_size/1e6:.1f} MB)")

    if not jf_counts.exists():
        print("Dumping counts...")
        run(["jellyfish", "dump", "-c", str(jf_db), "-o", str(jf_counts)])

    print("Loading counts...")
    kmer_count = {}
    with jf_counts.open() as fh:
        for line in fh:
            parts = line.strip().split()
            if len(parts) == 2:
                kmer_count[parts[0]] = int(parts[1])
    print(f"Loaded {len(kmer_count):,} k-mers")

    print("\n" + "-" * 80)
    print("UNITIGS")
    print("-" * 80)

    if not unitig_fa.exists():
        zst = outdir / f"{ACCESSION}.unitigs.fa.zst"
        if zst.exists():
            run(["zstd", "-d", "-f", str(zst), "-o", str(unitig_fa)])
    if not unitig_fa.exists():
        raise RuntimeError(f"Unitig FASTA missing: {unitig_fa}")

    unitigs = {}
    name, seq = None, []
    with unitig_fa.open() as fh:
        for line in fh:
            if line.startswith(">"):
                if name is not None:
                    m = re.search(r"(\d+)$", name)
                    if m:
                        unitigs[int(m.group(1))] = "".join(seq).upper()
                name = line[1:].split()[0]
                seq = []
            else:
                seq.append(line.strip())
        if name is not None:
            m = re.search(r"(\d+)$", name)
            if m:
                unitigs[int(m.group(1))] = "".join(seq).upper()
    print(f"Unitigs: {len(unitigs)}")

    print("\n" + "-" * 80)
    print("BOUNDARY K-MER READ SUPPORT")
    print("-" * 80)

    cand_by_branch = defaultdict(list)
    with candidates_csv.open() as fh:
        for r in csv.DictReader(fh):
            cand_by_branch[r["branch_key"]].append(r)

    read_choice_rows = []
    for branch_key, cands in cand_by_branch.items():
        if len(cands) < 2:
            continue
        uid = int(cands[0]["branch_unitig_id"])
        side = cands[0]["branch_side"]
        if uid not in unitigs:
            continue
        src = unitigs[uid]
        if side == "-":
            src = revcomp(src)
        if len(src) < BOUNDARY_CONTEXT_LEN:
            continue
        eval_context = src[-BOUNDARY_CONTEXT_LEN:]

        supports = []
        for c in cands:
            ext = c["extension"]
            if not ext or not re.fullmatch(r"[ACGT]+", ext):
                continue
            xe = eval_context + ext
            De = []
            c_len = len(eval_context)
            for t in range(c_len):
                if t + KMER_K > len(xe):
                    break
                if t + KMER_K - 1 >= c_len:
                    De.append(xe[t:t + KMER_K])
            R = sum(kmer_count.get(km, 0) for km in De)
            supports.append({
                "candidate_index": int(c["candidate_index"]),
                "extension": ext,
                "R": R,
            })

        if len(supports) < 2:
            continue
        supports.sort(key=lambda x: -x["R"])
        best, second = supports[0], supports[1]
        unique = best["R"] > 0 and best["R"] > second["R"]
        margin = (best["R"] / second["R"]) if second["R"] > 0 else (1e9 if best["R"] > 0 else 0.0)

        read_choice_rows.append({
            "branch_key": branch_key,
            "n_candidates": len(supports),
            "read_choice_index": best["candidate_index"],
            "read_choice_extension": best["extension"],
            "read_score": best["R"],
            "second_score": second["R"],
            "margin_ratio": margin,
            "unique": int(unique),
        })

    with read_choices_csv.open("w", newline="") as fh:
        fields = ["branch_key", "n_candidates", "read_choice_index",
                  "read_choice_extension", "read_score", "second_score",
                  "margin_ratio", "unique"]
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        for r in read_choice_rows:
            w.writerow(r)

    n_unique = sum(1 for r in read_choice_rows if r["unique"])
    print(f"Unique read-supported choices: {n_unique} / {len(read_choice_rows)}")

    print("\n" + "-" * 80)
    print("MATCH RATES")
    print("-" * 80)

    dec_index = {(d["branch_key"], d["context_length"]): d for d in decisions}
    read_index = {r["branch_key"]: r for r in read_choice_rows if r["unique"]}

    match_rows = []
    for ctx_len in CONTEXT_LENGTHS:
        matched = total = 0
        for bk, rd in read_index.items():
            d = dec_index.get((bk, ctx_len))
            if d is None:
                continue
            total += 1
            if d["selected_candidate_index"] == rd["read_choice_index"]:
                matched += 1
        overall = 100.0 * matched / total if total else 0.0
        row = {
            "context_length": ctx_len,
            "comparable_branches": total,
            "match_pct": round(overall, 2),
        }
        for T in MARGIN_THRESHOLDS:
            matched_t = total_t = 0
            for bk, rd in read_index.items():
                if rd["margin_ratio"] < T:
                    continue
                d = dec_index.get((bk, ctx_len))
                if d is None:
                    continue
                total_t += 1
                if d["selected_candidate_index"] == rd["read_choice_index"]:
                    matched_t += 1
            row[f"match_pct_margin>={T}"] = round(100.0 * matched_t / total_t, 2) if total_t else 0.0
            row[f"n_margin>={T}"] = total_t
        match_rows.append(row)
        print(f"n={ctx_len}: {row['match_pct']}%  "
              f"(≥5: {row.get('match_pct_margin>=5')}%, ≥10: {row.get('match_pct_margin>=10')}%)")

    with match_csv.open("w", newline="") as fh:
        fields = ["context_length", "comparable_branches", "match_pct"] + \
                 [f"match_pct_margin>={T}" for T in MARGIN_THRESHOLDS] + \
                 [f"n_margin>={T}" for T in MARGIN_THRESHOLDS]
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        for r in match_rows:
            w.writerow(r)

    summary = {
        "accession": ACCESSION,
        "n_unique_read_choices": n_unique,
        "n_read_choice_branches": len(read_choice_rows),
        "match_by_context": match_rows,
        "files": {
            "scored": str(scored_csv),
            "decisions": str(decisions_csv),
            "read_choices": str(read_choices_csv),
            "match": str(match_csv),
        },
    }
    with summary_json.open("w") as fh:
        json.dump(summary, fh, indent=2)

    print("\n" + "=" * 80)
    print("EVALUATION COMPLETE")
    print("=" * 80)
    print(json.dumps(summary, indent=2))
    return summary


if __name__ == "__main__":
    if not EVO2_PYTHON.exists():
        rebuild_evo2_environment()
    else:
        print("Evo2 environment already present:", EVO2_PYTHON)

    run([str(EVO2_PYTHON), "-c",
         "import torch; from evo2 import Evo2; "
         "assert torch.cuda.is_available(); "
         "print('Evo2 env OK, GPU:', torch.cuda.get_device_name(0))"])

    outdir = prepare_candidates()
    decisions = score_with_evo2(outdir)
    fetch_reads_and_evaluate(outdir, decisions)